services:

# Postgres as a main storage
  db:
    image: postgres
    container_name: uks_js_db
    ports:
      - "8001:5432"
    environment:
      - POSTGRES_PASSWORD=postuksjs
      - POSTGRES_USER=postuksjs

# Django application
  web:
    image: jsthegreat/uks-js
    container_name: uks_js_web
    labels:
      com.example.service: "web"
      com.example.description: "Use for the main web process"
    build: .
    command: ["wait-for-postgres.sh"]
    expose:
      - 8000
    volumes:
      - ./static:/code/static #must be same as nginx!
    depends_on:
      - db
    links:
      - redis
    environment:
      - POSTGRES_PASSWORD=postuksjs
      - POSTGRES_USER=postuksjs

# Nginx as a web server and reverse proxy
  nginx:
    image: nginx
    container_name: uks_js_nginx
    ports:
      - "8083:8083"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/code/static #must be same as web!
    depends_on:
      - web

# redis as a Django cache store
  redis:
    image: redis
    container_name: uks_js_redis
    expose:
      - '6379'